baseurl = "https://example.org"
title = "AS Partners"
theme = "hugo-universal-theme"
themesDir = "./"
languageCode = "pt-br"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "pt-br"
# Enable comments by entering your Disqus shortname
disqusShortname = "Prof. André Salerno, MSc"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-62383348-1"

logo = "img/logo.png"

favicon = "img/favicon.ico"

ignoreFiles = ["\\.rmd$", "_files$", "_cache$"]

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Blog"
    url  = "/blog/"
    weight = 2

#[[menu.main]]
#    name = "FAQ"
#    identifier = "faq"
#    url  = "/faq/"
#    weight = 3

[[menu.main]]
    name = "Contato"
    url  = "/contact/"
    weight = 4

# Top bar social links menu

#[[menu.topbar]]
#    weight = 1
#    name = "GitHub"
#    url = "https://github.com/devcows/hugo-universal-theme"
#    pre = "<i class='fa fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "https://www.facebook.com/aspartnersconsultoria/"
    pre = "<i class='fa fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "https://twitter.com/andresalerno"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:andresalerno22@gmail.com"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "Prof. André Salerno, MSc"
    defaultKeywords = ["finance", "R Programming", "Python", "Capital de Giro"]
    defaultDescription = "Site template made by devcows using hugo"

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = ""

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "green"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "andresalerno22@gmail.com"

    about_us = "<p>São mais de 20 anos de mercado financeiro, desenvolvidos dentro de áreas de crédito para pessoa física e jurídica. Isso nos possibilitou irmos além dentro da área financeira. Hoje desenvolvemos projetos estratégicos e com uso de tecnologias capazes de levar pessoas e empresas muito além das atuais fronteiras</p>"
    copyright = "Copyright (c) 2018 - 2019, AS Partners Finance & Tech Solutions; Todos os direitos reservados."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    address = """<p><strong>AS Partners Finance & Tech Solutions</strong>
        <br>Avenida Cassiano Ricardo, 319 - sala 508
        <br>Pátio das Américas
        <br>Jardim Aquarius
        <br>São José dos Campos - Brasil
        <br>
        <strong>Parahiba Valley</strong>
      </p>
      """
    latitude = "-23.2209236"
    longitude = "-45.9111879"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Procure a gente! Escreva para andresalerno22@gmail.com</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Gente que faz a diferença junto com a gente!"
    subtitle = "Nossas ideias tem sido somadas a de nossos clientes, parceiros e fornecedores. É nessa hora que os resultados conjuntos desafiam a matemática, e nossa experiência tem resultado em performance superior e vantagem competitiva sustentável"

[params.see_more]
    enable = true
    icon = "fa fa-file-code-o"
    title = "Conheça os nossos cursos!"
    subtitle = "Nossa bagagem profissional e acadêmica nos possibilitou criar cursos bem consistentes que permitem a sua efeitva aplicação nos mais variados ambientes de negóicos. E tudo isso, em um ambiente online que poder ser visto na palma da sua mão! Aproveite!"
    link_url = "https://www.udemy.com/mba-online-fintech-academy-modulo-em-financas/?src=sac&kw=fintech"
    link_text = "Confira aqui!"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = false
    title = "Espaço Conhecimento"
    subtitle = "É aqui que compartilhamos as nossas experiências. Confira abaixo alguns exemplos, mas tem muito mais por vir!"
